pipeline {
    agent any
    environment {
        // This assumes your Jenkins credential is of type "Username with password"
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
        // Jenkins will automatically set POSTGRES_SECRET_USR and POSTGRES_SECRET_PSW
    }
    stages {
        stage('Update Packages') {
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y libpq-dev'
            }
        }
        stage('Install Python') {
            steps {
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/tokarz23/dqe-automation'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r data_dev/requirements.txt
                    pip install pytest pytest-html
                '''
            }
        }
        stage('Run main') {
            steps {
                sh '''
                    . venv/bin/activate
                    export PYTHONPATH=$WORKSPACE
                    python data_dev/main.py
                '''
            }
        }
        stage('Run PyTest DQ Checks') {
            steps {
                sh '''
                    . venv/bin/activate
                    cd "PyTest_DQ_Framework"
                    pytest tests -m "parquet_data" \
                        --db_host="postgres" \
                        --db_port="5432" \
                        --db_name="mydatabase" \
                        --db_user=$POSTGRES_SECRET_USR \
                        --db_password=$POSTGRES_SECRET_PSW \
                        --html=html_report/index.html --self-contained-html
                '''
            }
        }
        stage('Archive Test Report') {
            steps {
                archiveArtifacts artifacts: 'PyTest_DQ_Framework/html_report/**', allowEmptyArchive: true

                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'PyTest_DQ_Framework/html_report',
                    reportFiles: 'index.html',
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed.'
        }

        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}